# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cmds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdprotocol', models.CharField(choices=[(0, ''), (1, 'REST API'), (2, 'SOAP'), (3, 'Telnet'), (4, 'TL1'), (5, 'SSH')], default=0, max_length=255)),
                ('cmdsystem', models.CharField(choices=[(0, ''), (1, 'AMS5520'), (2, 'AXSVision'), (3, 'Calix'), (4, 'JunOS'), (5, 'JunOSe')], default=0, max_length=255)),
                ('cmdset', models.CharField(default='', max_length=255)),
                ('cmdline', models.CharField(default='\n', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
