# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmdsets',
            name='cmdsystemkey',
        ),
        migrations.RemoveField(
            model_name='cmdsystems',
            name='cmdprotocolkey',
        ),
        migrations.RemoveField(
            model_name='cmds',
            name='cmdsetkey',
        ),
        migrations.AddField(
            model_name='cmds',
            name='cmdprotocol',
            field=models.CharField(choices=[(0, ''), (1, 'REST API'), (2, 'SOAP'), (3, 'Telnet'), (4, 'TL1'), (5, 'SSH')], default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='cmds',
            name='cmdsystem',
            field=models.CharField(choices=[(0, ''), (1, 'AMS5520'), (2, 'AXSVision'), (3, 'Calix'), (4, 'JunOS'), (5, 'JunOSe')], default=0, max_length=255),
        ),
        migrations.DeleteModel(
            name='CmdProtocols',
        ),
        migrations.DeleteModel(
            name='CmdSets',
        ),
        migrations.DeleteModel(
            name='CmdSystems',
        ),
    ]
