# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_auto_20170809_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmds',
            name='cmdline',
            field=models.CharField(default='\n', max_length=255),
        ),
        migrations.AlterField(
            model_name='cmds',
            name='cmdset',
            field=models.CharField(default='', max_length=255),
        ),
    ]
